name: Build

on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        default: ubuntu-latest
      dotnet-version:
        type: string
        default: 6.0.x
      solution:
        type: string
        default: ./src/*.sln
      test-results:
        type: string
        default: ./test-results
    
jobs:
  build:
    name: Build
    runs-on: ${{ inputs.runs-on }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup .NET ${{ inputs.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ inputs.dotnet-version }}          
      
      - name: Setup Testspace
        uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{github.repository_owner}}
        
      - name: Lint
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: develop
          FILTER_REGEX_EXCLUDE: .*github/**/*.*
          
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: csharp
          
      - name: Restore dependencies
        run: dotnet restore ${{ inputs.solution }}
        
      - name: Build
        run: dotnet build ${{ inputs.solution }} --no-restore
        
      - name: Test
        run: dotnet test ${{ inputs.solution }} --no-restore --collect "XPlat Code Coverage" --logger:"trx" --results-directory ${{ inputs.test-results }} --blame
        
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
      
      - name: Publish Test Results
        run: testspace ${{ inputs.test-results }}/*.trx
        