name: Build

on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        default: windows-latest
      dotnet-version:
        type: string
        default: 6.0.x
      solution:
        type: string
        default: src/
      test-results:
        type: string
        required: true
      test-runsettings:
        type: string
        default: environment/test.runsettings
      artifacts:
        type: string
        required: true
      publish-livingdoc-artifacts:
        type: boolean
        required: true
    secrets:
      SONAR_TOKEN:
        required: true
    
jobs:
  build:
    name: Build
    runs-on: ${{ inputs.runs-on }}
    
    steps:        
      - name: Setup .NET ${{ inputs.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ inputs.dotnet-version }}           
      
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
          
      - name: Checkout
        uses: actions/checkout@v3  
        with:
          fetch-depth: 0
      
      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
          
      - name: Cache SonarQube scanner
        id: cache-sonar-scanner
        uses: actions/cache@v1
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
          
      - name: Install SonarQube scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
      
      - name: Begin Analysis
        run: .\.sonar\scanner\dotnet-sonarscanner begin /k:"mihben_S-Train" /o:"mihben" /n:"S-Train" /d:sonar.dotnet.excludeTestProjects=true /d:sonar.cs.vstest.reportsPaths=${{ inputs.test-results }}/*.trx /d:sonar.sources=src/ /d:sonar.cs.opencover.reportsPaths=${{ inputs.test-results }}/**/*.xml /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
      
      - name: Restore dependencies
        run: dotnet restore ${{ inputs.solution }}
        
      - name: Build
        run: dotnet build ${{ inputs.solution }} --no-restore --output build/
        
      - name: Test
        run: dotnet test src/ --logger "trx" --output build/ --results-directory "${{ inputs.test-results }}" --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover --blame --settings "${{ inputs.test-runsettings }}"
        continue-on-error: true
        
      - name: Perform Code Analysis        
        run: .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
        
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        with:
          trx_files: "${{ inputs.test-results }}/**/*.trx"
          fail_on: "test_failures"
        
      - name: Copy Artifacts
        shell: powershell
        if: ${{ inputs.publish-livingdoc-artifacts == true }}
        run: |
          New-Item -Path "artifacts" -ItemType Directory
          Copy-Item -Path $(Get-ChildItem -Path build\*.Test.*.dll -Recurse),$(Get-ChildItem -Path build\TestExecution.json -Recurse) -Destination "artifacts" -Recurse
        
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        if: ${{ inputs.publish-livingdoc-artifacts == true }}
        with:
          path: artifacts/
          name: ${{ inputs.artifacts }}
