name: Build

on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        default: ubuntu-latest
      dotnet-version:
        type: string
        default: 6.0.x
      solution:
        type: string
        default: ./src/*.sln
      test-results:
        type: string
        default: ./test-results
    
jobs:
  build:
    name: Build
    runs-on: ${{ inputs.runs-on }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup .NET ${{ inputs.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
          
      - name: Restore dependencies
        run: dotnet restore ${{ inputs.solution }}
        
      - name: Build
        run: dotnet build ${{ inputs.solution }} --no-restore
        
      - name: Test
        run: dotnet test ${{ inputs.solution }} --no-restore --collect "XPlat Code Coverage" --logger:"trx" --results-directory ./test-results --blame
        
      - name: Publish Test Results
        uses: phoenix-actions/test-reporting@v8
        if: always()
        with:
          path: ${{ inputs.test-results }}/*.trx
          reporter: dotnet-trx
          fail-on-error: true