name: Publish LivingDoc

on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        default: ubuntu-latest
      branch:
        type: string
        required: true
      artifacts:
        type: string
        required: true
      language:
        type: string
        default: en
        required: true
      title:
        type: string
        required: true
      organization:
        type: string
        required: true
      project:
        type: string
        required: true
      work-item-prefix:
        type: string
        required: true
        default: issue-
      
    
jobs:
  build:
    name: Publish LivingDoc
    runs-on: ${{ inputs.runs-on }}
    
    steps:            
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        working-directory: artifacts
        with:
          name: ${{ inputs.artifacts }}
      
      # - name: Prepare
        # run: livingdoc test-assembly *.Test.*.dll --project-language ${{ inputs.language }} --title "${{ inputs.title }}" --project-name "${{ inputs.project }}" --work-item-url-template "https://github.com/${{ inputs.organization }}/${{ inputs.project }}/issues/{id}" --work-item-prefix "${{ inputs.work-item-prefix }}" --test-execution-json .\TestExecution.json --output "target/${{ inputs.project }}/${{ inputs.project }}.html"
        # working-directory: artifacts
      
      # - name: Push
        # uses: crazy-max/ghaction-github-pages@v3
        # with:
          # build_dir: artifacts
          # target_branch: ${{ inputs.branch }}